/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yao_study_java_jni_JNIProxy */

#ifndef _Included_com_yao_study_java_jni_JNIProxy
#define _Included_com_yao_study_java_jni_JNIProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yao_study_java_jni_JNIProxy
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yao_study_java_jni_JNIProxy_print
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
